import { IPlayer } from "interfaces"

export const players: IPlayer[] = [
  {
    id: "1",
    waiting: false,
    position: 1,
    color: "#FFB666",
    colorSecond: "#F7931E",
    chars: { strength: 0, agility: 0, intelligence: 0, endurance: 1 },
    armor: { currentArmor: 0, maxArmor: 10 },
    health: { currentHealth: 100, maxHealth: 100 },
    hunger: { currentHunger: 15, maxHunger: 15 },
    trash: 50,
    cash: 550,
    inventory: {
      capacityWeapon: 2,
      capacityBelt: 5,
      capacityBackpack: 12,
      belt: [],
      weapon: [],
      backpack: [],
    },
  },
  {
    id: "2",
    waiting: true,
    position: 13,
    color: "#A284BD",
    colorSecond: "#9370B2",
    chars: { strength: 0, agility: 0, intelligence: 0, endurance: 2 },
    health: { currentHealth: 1, maxHealth: 100 },
    armor: { currentArmor: 0, maxArmor: 10 },
    hunger: { currentHunger: 1, maxHunger: 15 },
    trash: 0,
    cash: 0,
    inventory: {
      capacityWeapon: 2,
      capacityBelt: 5,
      capacityBackpack: 12,
      belt: [],
      weapon: [],
      backpack: [],
    },
  },
  {
    id: "3",
    waiting: true,
    position: 7,
    color: "#87B9D8",
    colorSecond: "#70A7D7",
    chars: { strength: 0, agility: 0, intelligence: 0, endurance: 2 },
    health: { currentHealth: 100, maxHealth: 100 },
    armor: { currentArmor: 1, maxArmor: 10 },
    hunger: { currentHunger: 15, maxHunger: 15 },
    trash: 1000,
    cash: 1000,
    inventory: {
      capacityWeapon: 2,
      capacityBelt: 5,
      capacityBackpack: 12,
      belt: [],
      weapon: [],
      backpack: [],
    },
  },
  {
    id: "4",
    waiting: true,
    position: 19,
    color: "#6BCDA1",
    colorSecond: "#50CC79",
    chars: { strength: 0, agility: 0, intelligence: 0, endurance: 3 },
    health: { currentHealth: 0, maxHealth: 100 },
    armor: { currentArmor: 50, maxArmor: 50 },
    hunger: { currentHunger: 0, maxHunger: 10 },
    trash: 0,
    cash: 0,
    inventory: {
      capacityWeapon: 2,
      capacityBelt: 5,
      capacityBackpack: 12,
      belt: [],
      weapon: [],
      backpack: [],
    },
  },
]
